title: "Wilfrida Were"
author: "Wilfrida Were"
description: "Explore and be teachable <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Portfolio", file: "README.md"}
  - {title: "Blog", file: "blog.md"}
  - {title: "Contact", file: "contact.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/Wilfrida-Were"}
  - {title: LinkedIn, url: "https://www.linkedin.com/in/wilfridawere/"}
  - {title: Kaggle, url: "https://www.kaggle.com/wilfridawere/code"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
